{
 "title": "Custom K8s Dash",
 "description": "created dashboard to monitor Pods by Namespace",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node Disk Usage ( GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "100 - (\r\n  node_filesystem_avail_bytes{mountpoint=\"/var\"} \r\n  / \r\n  node_filesystem_size_bytes{mountpoint=\"/var\"}\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod by Namespace",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Counts by Namespace and Pod",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total) by (namespace, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}